# Generated by Django 5.0.2 on 2026-01-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('appointments', 'Appointments'), ('finance', 'Finance'), ('users', 'Users')], max_length=50)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('is_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
